highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://finbarr.dev
author: Finbarr Brady

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
# baseurl: /vitae/
title: Finbarr Brady's Resume
name: Finbarr Brady
email: orderly-hazing-0l@icloud.com
email_full: mailto:orderly-hazing-0l@icloud.com
website: https://finbarr.dev
website_full: https://finbarr.dev
github: fbradyirl    # eg. daattali
twitter: finbarrbrady   # eg. daattali
# tel: +44 0000 111111
# tel_full: tel:+440000000000
google_maps: 'https://maps.apple.com/?address=Galway,%20Ireland&auid=7812146429975975152&ll=53.275936,-9.042385&lsp=6489&q=Galway&t=m'
address:
  city: Galway
  country: Ireland

# needed for travis-ci build
exclude: [vendor]
